# Reading and Writing CS

In [1]:
import csv #csv 임포트

In [2]:
# 실수형 변수 확인을 위함 소숫점 밑에 두 자리까지 보여줌
%precision 2 

'%.2f'

In [3]:
# csv 파일 오픈 ,파일 위치 주의!
with open('car.csv') as csvfile:
    cars = list(csv.DictReader(csvfile))

In [4]:
# 처음부터 세개 까지 읽어들임
cars[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [5]:
# 전체 개수
len(cars)

234

In [6]:
# 1번째 요소의 key값 확인
cars[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [7]:
#전체 cty 연비의 평균
sum(float(d['cty'])for d in cars)/len(cars)

16.86

In [8]:
#전체 hwy 연비의 평균
sum(float(d['hwy'])for d in cars)/len(cars)

23.44

In [9]:
# cyl(기통) 종류
cylinder = set(d['cyl'] for d in cars)
cylinder

{'4', '5', '6', '8'}

In [10]:
CtyMpgByCyl = []

In [11]:
# cyl(기통) 마다의 평균, 도시연비
for c in cylinder:
    summpg = 0
    cyltypecount = 0
    
    for d in cars:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg/cyltypecount))
            
            

In [12]:
CtyMpgByCyl

[('6', 16.22), ('5', 20.50), ('4', 21.01), ('8', 12.57)]

In [13]:
# 결과 정렬
CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [14]:
vehicleclass = set(d['class'] for d in cars)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [15]:
HwyMpgByClass = []

In [16]:
# Class 마다 연비 평균
for c in vehicleclass:
    summpg = 0
    hwytypecount = 0
    
    for d in cars:
        if d['class'] == c:
            summpg += float(d['hwy'])
            hwytypecount += 1
    HwyMpgByClass.append((c, summpg/hwytypecount))
HwyMpgByClass

[('subcompact', 28.14),
 ('compact', 28.30),
 ('2seater', 24.80),
 ('suv', 18.13),
 ('midsize', 27.29),
 ('pickup', 16.88),
 ('minivan', 22.36)]

In [17]:
# 결과 정렬
HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

# The Python Programming : Dates and Time

In [18]:
import datetime as dt
import time as tm

In [19]:
# 시간 확인
tm.time()

1616225893.89

In [20]:
# 현재시간 확인
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow


datetime.datetime(2021, 3, 20, 16, 38, 13, 899642)

In [21]:
dtnow.month

3

In [22]:
dtnow.year

2021

In [23]:
# days 가 100 인 타임변수
delta = dt.timedelta(days = 100)

In [24]:
today = dt.date.today()
today

datetime.date(2021, 3, 20)

In [25]:
# delta 가 백일을 의미 하므로 이건 백일 전을 나타냄
today - delta

datetime.date(2020, 12, 10)

In [26]:
# date 타입도 비교연산이 가능하다
today > today -delta

True

# The Pythono Programming : Objects and map() funcion 

In [27]:
# Class 의 사용
class Person:
    department = 'Department of Computer Science'

    def set_name(self, new_name):
        self.name = new_name

In [28]:
person = Person()

In [29]:
person.set_name('ksshin')

In [30]:
print('{} in department {}'.format(person.name,person.department))

ksshin in department Department of Computer Science


In [31]:
# map의 사용
store1 = [10.00,11.00,12.34,2.34]
store2 = [9.00,11.10,12.34,2.87]

In [32]:
# map.put
cheapest = map(min,store1,store2)

In [33]:
# min의 주솟값이 나온다
cheapest

In [34]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.34


# The Python Programming : Numerical Python(NumPy)

In [35]:
# NumPY: 파이썬의 객체같은 것들을 Matrix화 하는 것 

In [36]:
import numpy as np

In [37]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [38]:
x = np.array(mylist)

In [39]:
x

array([1, 2, 3])

In [40]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [41]:
# 행렬 행.row 열.column
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [42]:
m.shape

(2, 3)

In [43]:
# Array 생성, 0~30 까지 2step 씩
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [44]:
# Array shape, Array의 형태를 바꿔줌 아래는 3행 5열로 바꿔줌
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [45]:
# 0부터 4까지 9개로 나누겠다.
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [46]:
# resize reshape과 유사하지만 resize는 연산 대상자체를 바꿔주는것, 
# reshape은 그냥 한번 연산을 해주는 것
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [47]:
# data를 1로 4행 3열에 채우겠다
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
# data를 0로 4행 3열에 채우겠다
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# diagonal(대각원소) 만 1로 채우는 것
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
y

array([4, 5, 6])

In [51]:
# diagonal 에 특수 숫자만 넣는 경우 _여기선 y를 넣었다
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [52]:
# 특정 숫자를 반복시켜 array를 만듬
np.array([123]*3)

array([123, 123, 123])

In [53]:
np.repeat([123],3)

array([123, 123, 123])

In [54]:
# 예제 사용을 위한 p생성
p = np.ones([2,3],int)

In [55]:
p

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
# p를 쌓는 stack
p1 = np.vstack([p,2*p])

In [57]:
p1

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [58]:
# 스택을 오른쪽에 쌓음
p2 = np.hstack([p,2*p])

In [59]:
p2

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [60]:
# 행렬의 사칙연산
x,y

(array([1, 2, 3]), array([4, 5, 6]))

In [61]:
x+y

array([5, 7, 9])

In [62]:
x-y

array([-3, -3, -3])

In [63]:
x*y  #각 엘리먼트들을 직접 곱하는것, 다른 프로그램과 다를 수 있다

array([ 4, 10, 18])

In [64]:
x.dot(y) #각 매치되는 엘리먼트 곱의 합

32

In [65]:
x/y

array([0.25, 0.4 , 0.5 ])

In [66]:
x**2

array([1, 4, 9], dtype=int32)

In [67]:
# transpos , 행과 열을 바꾸는 것
z = np.vstack([x,y])

In [68]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
# 트랜스포즈
z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
z.shape

(2, 3)

In [71]:
z.T.shape

(3, 2)

In [72]:
z.dtype

dtype('int32')

In [73]:
# Data Type 변경
z = z.astype('f')

In [74]:
z.dtype

dtype('float32')

In [75]:
z.min() #최소값 

1.0

In [76]:
z.argmin() #최저로 하게끔하는 argument 0.0

0